### ISSUE TITLE
Show which resources are blocking a cluster while trying to delete it

### ISSUE THREAD

**Issue by quodt** [crate/croud#284]
I just tried to delete a cluster, unfortunately I got this error:

```
Are you sure you want to delete the cluster? [yN] yes
==> Error: This cluster is in use by other resources. Please delete them first.
```

It'd cool to get a list of such resources to get an idea how to resolve this issue.

**Comment by MarkusH** [comment]
Good idea.

**Comment by chaudum** [comment]
This has been implemented as part of the API response in https://github.com/crate/cloud-api/pull/1285
