### ISSUE TITLE
command "croud organization users add --user 'userid' --role 'role' --org-id 'id' --sudo is not working under Windows 10

### ISSUE THREAD

**Issue by christianbader** [crate/croud#296]
Croud command add user to organization is not working with Microsoft Windows Cmd.exe, powerShell.exe and console.exe

I tried to add an user with

```json
croud me -o json
{
"email": "wolfgang@crate.io",
"hmac": "02b8b148816d9865ceb96c87e8aff8d3b34a3a6e4424d834dbdde7cb41e7f68e",
"is_superuser": true,
"name": null,
"organization_id": null,
"organization_roles": [],
"picture": null,
"project_roles": [],
"uid": "1c665ac9-adee-47a0-9018-8b83587b9426",
"username": "wolfgang@crate.io"
}
```

C:\WINDOWS\system32>croud organizations users add --user 1c665ac9-adee-47a0-9018-8b83587b9426 --role org_admin --org-id e8d23577-b9ed-4392-8a9d-bb259edd6c9f --sudo
==> Error: The last organization admin cannot change their organization role.

Same responses with cmd.exe, powershell.exe, console.exe

The command works with iTerm2 on maxOs.

**Comment by christianbader** [comment]
> The command works with iTerm2 on maxOs.

@WolfgangHerbst I don't think so, at least I can reproduce exact the same error on Mac OS X - would you mind to double check again?

I think this is a general bug. Since the user you are trying to add is currently not assigned to any other organization this command should work. If the user was assigned to another organization (an administrator) at the time this command was run, this answer would be correct.

**Comment by WolfgangHerbst** [comment]
@christianbader I double checked this behaviour with windows and Apple machine together, 
if the user is assigned to an organization the response is correct,
if the user is unassigned from the previous organization and will be a assigned to a new organizations than it doesn_t work -> by  my testing, the behaviour was only on the windows machine, on Mac it worked correct.
I've never tested this on Linux, if it would be helpful i will test on Linux, too.

**Comment by christianbader** [comment]
Seems that this was a backend issue which is fixed with https://github.com/crate/cloud-api/pull/1388.
Nevertheless, this doesn't explain why the os should have any impact.
If this error still occurs after the fix was released I'm happy to debug it again together.

**Comment by WolfgangHerbst** [comment]
@christianbader i've tested the version 0.24.0 > it work correct with Windows
